main = ".open-next/worker.js"
name = "ayts"
compatibility_date = "2026-01-22"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[env.production.vars]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://ayts-api.jerquinbayudo.workers.dev/"
 
NEXT_PUBLIC_SUPABASE_URL = "https://ssfygehaacargkkzouxr.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_Th-o5CO19aRn-S0zkDzEbA_5BIBnrf1"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY = "sb_publishable_Th-o5CO19aRn-S0zkDzEbA_5BIBnrf1"
 
NEXT_PUBLIC_APP_NAME = "AYTS"
NEXT_PUBLIC_APP_DESCRIPTION = "At Your Tayo Service - Your Local Marketplace"

[env.preview.vars]
NODE_ENV = "preview"


